import { 
  UserIcon, 
  FarmersDashboardIcon, 
  FarmersParcelsIcon, 
  FarmersLotsIcon, 
  FarmersHarvestIcon, 
  FarmersQrIcon, 
  FarmersTransactionIcon, 
  FarmersSupportIcon,
  StoreDashboardIcon,
  StoreMembersIcon,
  StoreAgentsIcon,
  StoreValidationIcon,
  StoreTransportIcon,
  StoreFraudIcon,
  StoreReportIcon,
  StoreBellIcon,
  StoreProfileIcon,
  StorePendingIcon,
  StoreHistoryIcon,
  StoreMissionIcon,
  StoreQrIcon,
  BuyerDashboardIcon,
  BuyerMarketIcon,
  BuyerTransactionIcon,
  BuyerTraceIcon,
  BuyerBlockchainIcon,
  BuyerTransportIcon,
  BuyerProfileIcon,
  BuyerComplianceIcon,
  BuyerScanIcon,
  BuyerReportIcon,
  BuyerTransfoIcon,
  OpDashboardIcon,
  OpDeliveryIcon,
  OpProfileIcon,
  OpMapIcon,
  OpScanIcon,
  OpHistoryIcon,
  OpTransfoIcon,
  OpInputIcon,
  OpOutputIcon,
  OpTraceIcon,
  OpAgentIcon,
  OpFarmerIcon,
  OpKycIcon,
  OpDataIcon,
  OpMissionIcon,
  OpSyncIcon,
  OpBellIcon,
  AdminDashboardIcon,
  AdminUsersIcon,
  AdminCoopIcon,
  AdminKycIcon,
  AdminBatchesIcon,
  AdminTxIcon,
  AdminFraudIcon,
  AdminBlockchainIcon,
  AdminReportIcon,
  AdminLogsIcon,
  AdminStatsIcon,
  AdminEudrIcon,
  AdminAuditIcon,
  AdminCertIcon,
  AdminProfileIcon,
  AdminBellIcon,
} from "../components/icons";

export interface NavItem {
  name?: string;
  path?: string;
  icon?: any;
  type?: 'link' | 'separator';
}

export const DASHBOARD_NAV_ITEMS: Record<string, NavItem[]> = {
  farmer: [
    { name: "Dashboard", path: "/farmers/dashboard", icon: FarmersDashboardIcon, type: 'link' },
    { name: "Mes parcelles", path: "/farmers/parcels", icon: FarmersParcelsIcon, type: 'link' },
    { name: "Mes lots", path: "/farmers/lots", icon: FarmersLotsIcon, type: 'link' },
    { name: "Récoltes", path: "/farmers/harvests", icon: FarmersHarvestIcon, type: 'link' },
    { type: 'separator' },
    { name: "Scanner QR", path: "/farmers/scan", icon: FarmersQrIcon, type: 'link' },
    { name: "Transactions", path: "/farmers/transactions", icon: FarmersTransactionIcon, type: 'link' },
    { type: 'separator' },
    { name: "Support", path: "/farmers/support", icon: FarmersSupportIcon, type: 'link' },
  ],
  store: [
    { name: "Dashboard", path: "/stores/dashboard", icon: StoreDashboardIcon, type: 'link' },
    { name: "Profil Coop", path: "/stores/profile", icon: StoreProfileIcon, type: 'link' },
    { type: 'separator' },
    { name: "Membres", path: "/stores/members", icon: StoreMembersIcon, type: 'link' },
    { name: "Agents", path: "/stores/agents", icon: StoreAgentsIcon, type: 'link' },
    { type: 'separator' },
    { name: "Parcelles à valider", path: "/stores/parcels/validation", icon: StoreValidationIcon, type: 'link' },
    { name: "Lots à vérifier", path: "/stores/batches/validation", icon: StoreQrIcon, type: 'link' },
    { name: "Demandes en attente", path: "/stores/pending", icon: StorePendingIcon, type: 'link' },
    { name: "Validations", path: "/stores/validations/history", icon: StoreHistoryIcon, type: 'link' },
    { type: 'separator' },
    { name: "Transporteurs", path: "/stores/transport/registry", icon: StoreTransportIcon, type: 'link' },
    { name: "Transports", path: "/stores/transport", icon: StoreTransportIcon, type: 'link' },
    { name: "Alertes fraude", path: "/stores/fraud", icon: StoreFraudIcon, type: 'link' },
    { name: "Transactions", path: "/stores/transactions", icon: FarmersTransactionIcon, type: 'link' },
    { type: 'separator' },
    { name: "Rapports", path: "/stores/reports", icon: StoreReportIcon, type: 'link' },
  ],
  "store-inspector": [
    { name: "Dashboard", path: "/stores/inspector/dashboard", icon: StoreDashboardIcon, type: 'link' },
    { name: "Missions", path: "/stores/inspector/missions", icon: StoreMissionIcon, type: 'link' },
    { type: 'separator' },
    { name: "Parcelles", path: "/stores/inspector/parcels", icon: StoreValidationIcon, type: 'link' },
    { name: "Lots", path: "/stores/inspector/batches", icon: StorePendingIcon, type: 'link' },
    { name: "Mes validations", path: "/stores/inspector/history", icon: StoreHistoryIcon, type: 'link' },
    { type: 'separator' },
    { name: "Scanner QR", path: "/stores/inspector/scan", icon: StoreQrIcon, type: 'link' },
    { name: "Rapports", path: "/stores/inspector/reports", icon: StoreReportIcon, type: 'link' },
  ],
  buyer: [
    { name: "Dashboard", path: "/buyers/dashboard", icon: BuyerDashboardIcon, type: 'link' },
    { name: "Mon profil", path: "/buyers/profile", icon: BuyerProfileIcon, type: 'link' },
    { type: 'separator' },
    { name: "Explorer les lots", path: "/buyers/market", icon: BuyerMarketIcon, type: 'link' },
    { name: "Mes achats", path: "/buyers/transactions", icon: BuyerTransactionIcon, type: 'link' },
    { type: 'separator' },
    { name: "Traçabilité", path: "/buyers/traceability", icon: BuyerTraceIcon, type: 'link' },
    { name: "Preuves Blockchain", path: "/buyers/blockchain", icon: BuyerBlockchainIcon, type: 'link' },
    { type: 'separator' },
    { name: "Transport", path: "/buyers/transport", icon: BuyerTransportIcon, type: 'link' },
    { name: "Transporteurs", path: "/buyers/transport/registry", icon: BuyerTransportIcon, type: 'link' },
    { name: "Transformations", path: "/buyers/transformations", icon: BuyerTransfoIcon, type: 'link' },
  ],
  "buyer-importateur": [
    { name: "Dashboard", path: "/buyers/dashboard", icon: BuyerDashboardIcon, type: 'link' },
    { name: "Conformité EUDR", path: "/buyers/compliance", icon: BuyerComplianceIcon, type: 'link' },
    { type: 'separator' },
    { name: "Traçabilité", path: "/buyers/traceability", icon: BuyerTraceIcon, type: 'link' },
    { name: "Preuves Blockchain", path: "/buyers/blockchain", icon: BuyerBlockchainIcon, type: 'link' },
    { type: 'separator' },
    { name: "Lots importés", path: "/buyers/imports", icon: BuyerTransactionIcon, type: 'link' },
    { name: "Scanner QR", path: "/buyers/scan", icon: BuyerScanIcon, type: 'link' },
    { type: 'separator' },
    { name: "Rapports conformité", path: "/buyers/compliance/reports", icon: BuyerReportIcon, type: 'link' },
  ],
  transporter: [
    { name: "Dashboard", path: "/transporters/dashboard", icon: OpDashboardIcon, type: 'link' },
    { name: "Mon profil", path: "/transporters/profile", icon: OpProfileIcon, type: 'link' },
    { type: 'separator' },
    { name: "Mes transports", path: "/transporters/deliveries", icon: OpDeliveryIcon, type: 'link' },
    { name: "En attente", path: "/transporters/pending", icon: OpDeliveryIcon, type: 'link' },
    { name: "Suivi", path: "/transporters/tracking", icon: OpMapIcon, type: 'link' },
    { type: 'separator' },
    { name: "Scanner QR", path: "/transporters/scan", icon: OpScanIcon, type: 'link' },
    { name: "Historique", path: "/transporters/history", icon: OpHistoryIcon, type: 'link' },
  ],
  processor: [
    { name: "Dashboard", path: "/processors/dashboard", icon: OpDashboardIcon, type: 'link' },
    { name: "Mes assignations", path: "/processors/assignments", icon: OpTransfoIcon, type: 'link' },
    { type: 'separator' },
    { name: "Lots entrants", path: "/processors/inputs", icon: OpInputIcon, type: 'link' },
    { name: "Lots sortants", path: "/processors/outputs", icon: OpOutputIcon, type: 'link' },
    { type: 'separator' },
    { name: "Historique", path: "/processors/history", icon: OpHistoryIcon, type: 'link' },
    { name: "Traçabilité", path: "/processors/traceability", icon: OpTraceIcon, type: 'link' },
  ],
  agent: [
    { name: "Dashboard", path: "/agents/dashboard", icon: OpAgentIcon, type: 'link' },
    { type: 'separator' },
    { name: "Créer farmer", path: "/agents/create-farmer", icon: OpFarmerIcon, type: 'link' },
    { name: "Capture KYC", path: "/agents/kyc", icon: OpKycIcon, type: 'link' },
    { name: "Parcelles", path: "/agents/parcels", icon: OpMissionIcon, type: 'link' },
    { name: "Saisie données", path: "/agents/data", icon: OpDataIcon, type: 'link' },
    { name: "Missions", path: "/agents/missions", icon: OpMissionIcon, type: 'link' },
    { type: 'separator' },
    { name: "Synchronisation", path: "/agents/sync", icon: OpSyncIcon, type: 'link' },
  ],
  admin: [
    { name: "Dashboard", path: "/admin/dashboard", icon: AdminDashboardIcon, type: 'link' },
    { type: 'separator' },
    { name: "Utilisateurs", path: "/admin/users", icon: AdminUsersIcon, type: 'link' },
    { name: "Magasins", path: "/admin/stores", icon: AdminCoopIcon, type: 'link' },
    { name: "KYC", path: "/admin/kyc", icon: AdminKycIcon, type: 'link' },
    { type: 'separator' },
    { name: "Lots", path: "/admin/batches", icon: AdminBatchesIcon, type: 'link' },
    { name: "Transactions", path: "/admin/transactions", icon: AdminTxIcon, type: 'link' },
    { name: "Alertes fraude", path: "/admin/fraud", icon: AdminFraudIcon, type: 'link' },
    { name: "Blockchain", path: "/admin/blockchain", icon: AdminBlockchainIcon, type: 'link' },
    { type: 'separator' },
    { name: "Rapports", path: "/admin/reports", icon: AdminReportIcon, type: 'link' },
    { name: "Logs système", path: "/admin/logs", icon: AdminLogsIcon, type: 'link' },
  ],
  "admin-gouvernement": [
    { name: "Dashboard national", path: "/gov/dashboard", icon: AdminDashboardIcon, type: 'link' },
    { name: "Stats production", path: "/gov/stats", icon: AdminStatsIcon, type: 'link' },
    { type: 'separator' },
    { name: "Traçabilité", path: "/gov/trace", icon: AdminBatchesIcon, type: 'link' },
    { name: "Blockchain", path: "/gov/blockchain", icon: AdminBlockchainIcon, type: 'link' },
    { name: "EUDR", path: "/gov/eudr", icon: AdminEudrIcon, type: 'link' },
    { type: 'separator' },
    { name: "Audit", path: "/gov/audit", icon: AdminAuditIcon, type: 'link' },
    { name: "Rapports", path: "/gov/reports", icon: AdminReportIcon, type: 'link' },
  ],
  "admin-certificateur": [
    { name: "Dashboard", path: "/cert/dashboard", icon: AdminDashboardIcon, type: 'link' },
    { name: "Certifications", path: "/cert/certifications", icon: AdminCertIcon, type: 'link' },
    { type: 'separator' },
    { name: "Parcelles", path: "/cert/parcels", icon: AdminStatsIcon, type: 'link' },
    { name: "Lots", path: "/cert/batches", icon: AdminBatchesIcon, type: 'link' },
    { name: "Blockchain", path: "/cert/blockchain", icon: AdminBlockchainIcon, type: 'link' },
    { type: 'separator' },
    { name: "Rapports", path: "/cert/reports", icon: AdminReportIcon, type: 'link' },
  ],
};
